/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-FeelGoodInc-FyWfvabnMmbqU3eXibgN1koDwypT4v8h",
  "version": "2020-11-20"
}

export default ebconfig;